services:
  es-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=banking-es'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  read-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=banking'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'

  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - 5672:5672
      - 15672:15672
